### ISSUE TITLE
cstor-pool container unable to start due to libjson-c.so.2

### ISSUE THREAD

**Issue by xunholy** [openebs/libcstor#61]
# Description

I got some strange errors about the libjson library. Apologies if this is in the wrong repository.

❯ k logs cstor-sparse-pool-w39i-65b4d88bbf-f4mzd cstor-pool
Disabling dumping core
sleeping for 2 sec
/usr/local/bin/zrepl: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory

**Environment:**
- OpenEBS version: 1.9.0 (Also tried using 1.10.x.RC2)
- Kubernetes version: 1.18.x
- OS: Ubuntu 20.04 Focal
- Hardware: Raspberry Pi 4B

**Comment by kmova** [comment]
Tracked under https://github.com/openebs/openebs/issues/3037
